const audited = (title, category, source, stories) => stories.map(([id, name, states = ["default"]]) => ({
  applicableStates: states,
  category,
  id,
  name,
  note: "Rendered in the automated Light/Dark viewport matrix.",
  source,
  status: "Ready",
  title,
}));

export const storyAuditManifest = [
  ...audited("01 Foundations/Foundation Preview", "Foundations", "./src/foundations/FoundationPreview.stories.tsx", [
    ["01-foundations-foundation-preview--workspace-foundation", "Workspace Foundation", ["default", "focus-visible"]],
    ["01-foundations-foundation-preview--system-theme-runtime", "System Theme Runtime", ["light", "dark", "system"]],
  ]),
  ...audited("02 Tokens/Token Catalog", "Foundations", "./src/tokens/TokenCatalog.stories.tsx", [
    ["02-tokens-token-catalog--dark-foundations", "Dark Foundations", ["dark"]],
    ["02-tokens-token-catalog--light-foundations", "Light Foundations", ["light"]],
    ["02-tokens-token-catalog--reduced-motion-and-focus", "Reduced Motion And Focus", ["reduced-motion", "focus-visible"]],
    ["02-tokens-token-catalog--narrow-reflow", "Narrow Reflow", ["narrow"]],
  ]),
  ...audited("03 Typography/Typography Preview", "Foundations", "./src/typography/TypographyPreview.stories.tsx", [
    ["03-typography-typography-preview--pulmu-content", "Pulmu Content"],
    ["03-typography-typography-preview--missing-preferred-font", "Missing Preferred Font", ["fallback"]],
    ["03-typography-typography-preview--narrow-reflow", "Narrow Reflow", ["narrow"]],
  ]),
  ...audited("04 Icons/Icon Catalog", "Foundations", "./src/icons/IconCatalog.stories.tsx", [
    ["04-icons-icon-catalog--iconography", "Dark iconography", ["dark"]],
    ["04-icons-icon-catalog--light-iconography", "Light Iconography", ["light"]],
    ["04-icons-icon-catalog--reduced-motion", "Reduced Motion", ["reduced-motion"]],
    ["04-icons-icon-catalog--narrow-reflow", "Narrow Reflow", ["narrow"]],
  ]),
  ...audited("05 Core Components/Components", "Core components", "./src/core/CoreComponents.stories.tsx", [
    ["05-core-components-components--button-story", "Button", ["default", "hover", "focus-visible", "active", "disabled", "loading"]],
    ["05-core-components-components--button-light-states", "Button Light States", ["light", "hover", "focus-visible", "active", "disabled", "loading"]],
    ["05-core-components-components--light-semantic-state-matrix", "Light Semantic State Matrix", ["light", "success", "warning", "danger", "information"]],
    ["05-core-components-components--dark-semantic-state-matrix", "Dark Semantic State Matrix", ["dark", "success", "warning", "danger", "information"]],
    ["05-core-components-components--icon-button-story", "IconButton", ["default", "hover", "focus-visible", "disabled"]],
    ["05-core-components-components--link-story", "Link", ["default", "hover", "focus-visible"]],
    ["05-core-components-components--input-story", "Input", ["default", "focus-visible", "disabled", "error"]],
    ["05-core-components-components--search-field-story", "SearchField", ["default", "focus-visible", "disabled"]],
    ["05-core-components-components--select-story", "Select", ["default", "focus-visible", "disabled"]],
    ["05-core-components-components--checkbox-story", "Checkbox", ["default", "checked", "focus-visible", "disabled"]],
    ["05-core-components-components--switch-story", "Switch", ["default", "checked", "focus-visible", "disabled"]],
    ["05-core-components-components--tabs-story", "Tabs", ["default", "selected", "focus-visible"]],
    ["05-core-components-components--manual-tabs-keyboard", "Manual Tabs Keyboard", ["keyboard", "selected"]],
    ["05-core-components-components--vertical-tabs-keyboard", "Vertical Tabs Keyboard", ["keyboard", "selected"]],
    ["05-core-components-components--controlled-dynamic-tabs", "Controlled Dynamic Tabs", ["controlled", "selected"]],
    ["05-core-components-components--badge-story", "Badge", ["default", "success", "warning", "danger"]],
    ["05-core-components-components--avatar-story", "Avatar", ["image", "fallback"]],
    ["05-core-components-components--card-story", "Card"],
    ["05-core-components-components--progress-story", "Progress", ["default", "loading"]],
    ["05-core-components-components--progress-boundaries", "Progress Boundaries", ["empty", "complete"]],
    ["05-core-components-components--spinner-story", "Spinner", ["loading"]],
    ["05-core-components-components--skeleton-story", "Skeleton", ["loading"]],
    ["05-core-components-components--tooltip-story", "Tooltip", ["closed", "hover", "focus-visible", "open"]],
    ["05-core-components-components--popover-story", "Popover", ["closed", "open", "keyboard"]],
    ["05-core-components-components--menu-story", "Menu", ["closed", "open", "keyboard", "disabled"]],
    ["05-core-components-components--dialog-story", "Dialog", ["closed", "open", "keyboard"]],
    ["05-core-components-components--alert-story", "Alert", ["information", "success", "warning", "danger"]],
    ["05-core-components-components--empty-state-story", "EmptyState", ["empty"]],
    ["05-core-components-components--error-state-story", "ErrorState", ["error"]],
    ["05-core-components-components--pagination-story", "Pagination", ["default", "current", "disabled"]],
    ["05-core-components-components--breadcrumb-story", "Breadcrumb", ["default", "current"]],
    ["05-core-components-components--copy-button-story", "CopyButton", ["default", "copied", "focus-visible"]],
    ["05-core-components-components--code-reference-story", "CodeReference", ["default", "overflow"]],
    ["05-core-components-components--visually-hidden-story", "VisuallyHidden"],
    ["05-core-components-components--skip-link-story", "SkipLink", ["hidden", "focus-visible"]],
    ["05-core-components-components--maturity-overview", "Maturity Overview"],
    ["05-core-components-components--narrow-content-coverage", "Narrow Content Coverage", ["narrow"]],
    ["05-core-components-components--overlay-edge-coverage", "Overlay Edge Coverage", ["open", "viewport-edge"]],
  ]),
  ...audited("06 Data Components/Components", "Data", "./src/data/DataComponents.stories.tsx", [
    ["06-data-components-components--semantic-table-and-filters", "Semantic Table And Filters", ["default", "sorted", "filtered", "overflow"]],
    ["06-data-components-components--metrics-and-progress", "Metrics And Progress", ["default", "positive", "negative"]],
    ["06-data-components-components--accessible-visualizations", "Accessible Visualizations", ["default", "data-table"]],
    ["06-data-components-components--loading-empty-error-and-stale", "Loading Empty Error And Stale", ["loading", "empty", "error", "stale"]],
  ]),
  ...audited("07 Forge Components/Forge Status", "Pulmu workflow", "./src/forge/ForgeComponents.stories.tsx", [
    ["07-forge-components-forge-status--running-hammer", "Running Hammer", ["in-progress"]],
    ["07-forge-components-forge-status--pattern-disabled", "Pattern Disabled", ["conditional-disabled"]],
    ["07-forge-components-forge-status--completed", "Completed", ["completed"]],
    ["07-forge-components-forge-status--failed-quench", "Failed Quench", ["failed"]],
    ["07-forge-components-forge-status--interrupted-hammer", "Interrupted Hammer", ["interrupted"]],
    ["07-forge-components-forge-status--provisional-metadata", "Provisional Metadata", ["provisional"]],
    ["07-forge-components-forge-status--quench-retry", "Quench Retry", ["retry"]],
    ["07-forge-components-forge-status--hone-refinement", "Hone Refinement", ["finding", "retry"]],
    ["07-forge-components-forge-status--verification-states", "Verification States", ["pending", "pass", "fail"]],
    ["07-forge-components-forge-status--review-states", "Review States", ["pass", "finding"]],
    ["07-forge-components-forge-status--delivery-states", "Delivery States", ["local", "github", "failed"]],
    ["07-forge-components-forge-status--narrow-long-content", "Narrow Long Content", ["narrow", "long-content"]],
    ["07-forge-components-forge-status--boundary-width-rail", "Boundary Width Rail", ["boundary-width"]],
  ]),
  ...audited("08 Agent Components/Agent Surfaces", "Pulmu workflow", "./src/agents/AgentComponents.stories.tsx", [
    ["08-agent-components-agent-surfaces--identity-authority-and-status", "Identity Authority And Status", ["active", "inactive"]],
    ["08-agent-components-agent-surfaces--no-active-agents", "No Active Agents", ["empty"]],
    ["08-agent-components-agent-surfaces--active-and-parallel-groups", "Active And Parallel Groups", ["active", "parallel"]],
    ["08-agent-components-agent-surfaces--quick-forge", "Quick Forge", ["quick", "pattern"]],
    ["08-agent-components-agent-surfaces--standard-forge", "Standard Forge", ["standard"]],
    ["08-agent-components-agent-surfaces--full-forge-with-conditional-reviewers", "Full Forge With Conditional Reviewers", ["full", "conditional"]],
    ["08-agent-components-agent-surfaces--pattern-designer", "Pattern Designer", ["pattern"]],
    ["08-agent-components-agent-surfaces--reviewer-findings", "Reviewer Findings", ["pass", "finding"]],
    ["08-agent-components-agent-surfaces--mobile-multiple-agents", "Mobile Multiple Agents", ["mobile", "parallel"]],
    ["08-agent-components-agent-surfaces--narrow-long-agent-names", "Narrow Long Agent Names", ["narrow", "long-content"]],
    ["08-agent-components-agent-surfaces--narrow-light-theme", "Narrow Light Theme", ["narrow", "light"]],
    ["08-agent-components-agent-surfaces--narrow-dark-theme", "Narrow Dark Theme", ["narrow", "dark"]],
  ]),
  ...audited("09 Layout Patterns/Responsive workspace", "Layout", "./src/layout/LayoutPatterns.stories.tsx", [
    ["09-layout-patterns-responsive-workspace--desktop-1440", "Desktop 1440", ["desktop"]],
    ["09-layout-patterns-responsive-workspace--tablet-768", "Tablet 768", ["tablet"]],
    ["09-layout-patterns-responsive-workspace--mobile-390", "Mobile 390", ["mobile"]],
    ["09-layout-patterns-responsive-workspace--narrow-320", "Narrow 320", ["narrow"]],
    ["09-layout-patterns-responsive-workspace--desktop-sidebar-keyboard", "Desktop Sidebar Keyboard", ["desktop", "keyboard"]],
    ["09-layout-patterns-responsive-workspace--mobile-sidebar-keyboard", "Mobile Sidebar Keyboard", ["mobile", "keyboard", "open"]],
    ["09-layout-patterns-responsive-workspace--mobile-sidebar-resize-recovery", "Mobile Sidebar Resize Recovery", ["mobile", "resize"]],
    ["09-layout-patterns-responsive-workspace--feedback-states", "Feedback States", ["loading", "empty", "error"]],
    ["09-layout-patterns-responsive-workspace--embedded-workspace", "Embedded Workspace", ["embedded"]],
  ]),
  ...audited("10 Example Screens/Component Map", "Example screens", "./src/screens/ComponentMap.stories.tsx", [
    ["10-example-screens-component-map--desktop-1440", "Desktop 1440", ["desktop", "light", "dark"]],
    ["10-example-screens-component-map--tablet-768", "Tablet 768", ["tablet", "light", "dark"]],
    ["10-example-screens-component-map--mobile-390", "Mobile 390", ["mobile", "light", "dark"]],
    ["10-example-screens-component-map--narrow-320", "Narrow 320", ["narrow", "light", "dark"]],
  ]),
  ...audited("10 Example Screens/Empty Workspace", "Example screens", "./src/screens/EmptyWorkspace.stories.tsx", [
    ["10-example-screens-empty-workspace--empty-workspace", "Empty Workspace", ["empty", "desktop"]],
    ["10-example-screens-empty-workspace--empty-workspace-mobile-390", "Empty Workspace · Mobile · 390", ["empty", "mobile"]],
  ]),
  ...audited("10 Example Screens/Workspace Overview", "Example screens", "./src/screens/Overview.stories.tsx", [
    ["10-example-screens-workspace-overview--light", "Light · Desktop · 1440", ["light", "desktop"]],
    ["10-example-screens-workspace-overview--dark", "Dark · Desktop · 1440", ["dark", "desktop"]],
    ["10-example-screens-workspace-overview--light-tablet-768", "Light · Tablet · 768", ["light", "tablet"]],
    ["10-example-screens-workspace-overview--tablet-768", "Dark · Tablet · 768", ["dark", "tablet"]],
    ["10-example-screens-workspace-overview--light-mobile-390", "Light · Mobile · 390", ["light", "mobile"]],
    ["10-example-screens-workspace-overview--mobile-390", "Dark · Mobile · 390", ["dark", "mobile"]],
    ["10-example-screens-workspace-overview--light-narrow-320", "Light · Narrow · 320", ["light", "narrow"]],
    ["10-example-screens-workspace-overview--narrow-320", "Dark · Narrow · 320", ["dark", "narrow"]],
    ["10-example-screens-workspace-overview--loading", "Loading", ["loading"]],
    ["10-example-screens-workspace-overview--empty", "Empty", ["empty"]],
    ["10-example-screens-workspace-overview--error", "Error", ["error"]],
    ["10-example-screens-workspace-overview--stale", "Stale", ["stale"]],
  ]),
  ...audited("10 Example Screens/Forge Runs", "Example screens", "./src/screens/RunDetailScreens.stories.tsx", [
    ["10-example-screens-forge-runs--active-forge-run", "Active Forge Run", ["active", "desktop"]],
    ["10-example-screens-forge-runs--active-forge-run-tablet-768", "Active Forge Run · Tablet · 768", ["active", "tablet"]],
    ["10-example-screens-forge-runs--active-forge-run-mobile-390", "Active Forge Run · Mobile · 390", ["active", "mobile"]],
    ["10-example-screens-forge-runs--active-forge-run-narrow-320", "Active Forge Run · Narrow · 320", ["active", "narrow"]],
    ["10-example-screens-forge-runs--quench-retry", "Quench Retry", ["retry"]],
    ["10-example-screens-forge-runs--hone-review-finding", "Hone Review Finding", ["finding"]],
    ["10-example-screens-forge-runs--completed-local-delivery", "Completed Local Delivery", ["completed", "local"]],
    ["10-example-screens-forge-runs--completed-git-hub-delivery", "Completed Git Hub Delivery", ["completed", "github"]],
    ["10-example-screens-forge-runs--failed-run", "Failed Run", ["failed"]],
    ["10-example-screens-forge-runs--interrupted-run", "Interrupted Run", ["interrupted"]],
  ]),
  ...audited("10 Example Screens/Run History", "Example screens", "./src/screens/RunHistory.stories.tsx", [
    ["10-example-screens-run-history--run-history", "Run History", ["default", "desktop"]],
    ["10-example-screens-run-history--run-history-narrow-320", "Run History · Narrow · 320", ["narrow"]],
    ["10-example-screens-run-history--loading", "Loading", ["loading"]],
    ["10-example-screens-run-history--stale", "Stale", ["stale"]],
  ]),
];

export const missingCapabilities = [
  { category: "Overlays", name: "Drawer", note: "No standalone published API; compact navigation composes Dialog.", status: "Missing" },
  { category: "Overlays", name: "Toast", note: "No standalone published API or announcement contract yet.", status: "Missing" },
];
